spring.application.name=gym

################
# Log Config
################
logging.level.root=info
logging.pattern.console=%date{dd MMM yyyy;HH:mm:ss.SSS}  %highlight(%-5level) %cyan(%logger{36}) - %green(%msg%n)
logging.path.url=logs
logging.file.name=${logging.path.url}/app_log.log
logging.pattern.file=%date{dd MMM yyyy - HH:mm:ss.SSS} - %logger{36} -  %-5level - %msg%n
logging.logback.rollingpolicy.max-file-size=500KB

################
# Values
################
password.characters=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
################
# Spring Data Config
################
spring.datasource.url=jdbc:postgresql://ep-billowing-mud-aiprlmtr-pooler.c-4.us-east-1.aws.neon.tech/gymdb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_i5YXrGbqfPT2
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
##################
# Flyway Config
#################
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baselineVersion=0
