####    //    3. Login (GET method)

POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "username": "Ann.Miller",
    "password": "kY6ZZqkYtS"
 }

#####    4. Change Login (PUT method)
POST localhost:8080/api/v1/auth/public/change-password
Content-Type: application/json

{
  "username": "Mike.Smith",
  "oldPassword": "XSx2ZNQBIL",
  "newPassword": "Toshiba_1990$"
}