### 14. Add Training (POST method)

POST localhost:8080/api/v1/training
Content-Type: application/json

{
  "trainerUsername": "Ali.Aliyev_trainer",
  "traineeUsername": "Ann.Miller",
  "trainingDate": "2020-01-01",
  "trainingDuration": 60,
  "trainingTypeId": 3
}

### 12. Get Trainee Trainings List (GET method)

POST localhost:8080/api/v1/training/trainee
Content-Type: application/json

{
  "traineeUsername": "Ann.Miller",
  "trainerName": "Ali.Aliyev_trainer"
}

### 13. Get Trainer Trainings List (GET method)

POST localhost:8080/api/v1/training/trainer
Content-Type: application/json

{
  "trainerUsername": "Ali.Aliyev_trainer"
}

